"""empty message

Revision ID: 8871804eebaf
Revises: 
Create Date: 2023-04-10 16:40:31.107445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8871804eebaf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('isbn', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=True),
    sa.Column('author_fname', sa.String(length=150), nullable=True),
    sa.Column('author_lname', sa.String(length=150), nullable=True),
    sa.Column('length_', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(length=150), nullable=True),
    sa.Column('binding', sa.String(length=10), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('isbn')
    )
    op.create_table('librarian',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lib_fname', sa.String(length=150), nullable=True),
    sa.Column('lib_lname', sa.String(length=150), nullable=True),
    sa.Column('lib_email', sa.String(length=150), nullable=False),
    sa.Column('lib_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('fname', sa.String(length=150), nullable=False),
    sa.Column('lname', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('book_status',
    sa.Column('trans_id', sa.String(), nullable=False),
    sa.Column('checkout_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('isbn', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['isbn'], ['books.isbn'], ),
    sa.PrimaryKeyConstraint('trans_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_status')
    op.drop_table('user')
    op.drop_table('librarian')
    op.drop_table('books')
    # ### end Alembic commands ###
