"""empty message

Revision ID: e335e00a6528
Revises: 8871804eebaf
Create Date: 2023-04-12 16:01:43.790050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e335e00a6528'
down_revision = '8871804eebaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('librarian', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['pin'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('fname',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('lname',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)
        batch_op.alter_column('lname',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('fname',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    with op.batch_alter_table('librarian', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
